const RESET = 'APP_RESET';

/* Authentication Keys */
const LOGIN_REQUST = 'LOGIN_REQUST';
const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
const LOGIN_REQUST_ERROR = 'LOGIN_REQUST_ERROR';

/* Analytics Keys */
const DATA_REQUST = 'DATA_REQUST';
const DATA_REQUEST_SUCCESS = 'DATA_REQUEST_SUCCESS';
const DATA_REQUST_ERROR = 'DATA_REQUST_ERROR';

export default {
  LOGIN_REQUST,
  LOGIN_REQUEST_SUCCESS,
  LOGIN_REQUST_ERROR,
  DATA_REQUST,
  DATA_REQUEST_SUCCESS,
  DATA_REQUST_ERROR,
  RESET,
};
